### ISSUE TITLE
Could this be Idempotent?

### ISSUE THREAD

**Issue by tapickell** [jeremyfa/yaml.js#48]
If you call `YAML.parse(myObject);` passing it an object it blows up.

```
TypeError: undefined is not a function
    at Parser.cleanup (/Users//code/tag-validation-lambda/node_modules/yamljs/lib/Parser.js:532:15)
    at Parser.parse (/Users//code/tag-validation-lambda/node_modules/yamljs/lib/Parser.js:65:23)
    at Function.Yaml.parse (/Users//code/tag-validation-lambda/node_modules/yamljs/lib/Yaml.js:20:25)
    at repl:1:6
    at REPLServer.defaultEval (repl.js:132:27)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:279:12)
    at REPLServer.emit (events.js:107:17)
    at REPLServer.Interface._onLine (readline.js:214:10)
```

I am just proposing that maybe this could be idempotent and simply return any thing that is already an object instead of a getting a stacktrace.

**Comment by jeremyfa** [comment]
The error is indeed not very understandable.

That said, parsing yaml is about parsing a string, not an object. Thus, instead of accepting any object as you requested, it should raise a clearer error explaining what is wrong: input should be a valid yaml string.

You can always create a wrapper that does return the object as is when it isn't a string, even though I believe this could hide some other underlying error in the project that ended up in trying to parse something that is not a yaml string.

Anyway, this logic should not be part of the yaml library.

The error not being clear enough is still an issue that should be fixed however.

Thanks for the feedback!

**Comment by joao-parana** [comment]
I totally agree with @jeremyfa
